-- Preserve the server-only data-access contract established in 0003.
-- Clerk authorization runs in the API; Supabase client roles get no direct
-- application-table access. The server database owner continues to bypass RLS.
-- Scope is the explicit application schema; unrelated schemas/tables are untouched.
DO $$
DECLARE
  table_name text;
  client_role text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'activity_log',
    'agent_api_keys',
    'agent_collaborations',
    'agent_config_revisions',
    'agent_evaluations',
    'agent_executions',
    'agent_files',
    'agent_memories',
    'agent_runtime_sessions',
    'agent_skills',
    'agents',
    'approval_comments',
    'approvals',
    'artifact_folders',
    'artifact_permissions',
    'artifact_provenance',
    'artifact_revisions',
    'artifact_templates',
    'artifacts',
    'automation_runs',
    'budget_alerts',
    'budget_allocations',
    'budget_reservations',
    'budget_settlements',
    'citation_carry_forward_outcomes',
    'citations',
    'companies',
    'company_invitations',
    'company_members',
    'company_skills',
    'company_templates',
    'cost_events',
    'execution_environments',
    'goals',
    'heartbeats',
    'inbox_read_states',
    'integrations',
    'knowledge_chunks',
    'knowledge_documents',
    'local_trusted_sessions',
    'mcp_servers',
    'mcp_tool_calls',
    'meeting_tasks',
    'meetings',
    'messages',
    'mission_runs',
    'mission_worker_heartbeats',
    'mode_profiles',
    'project_decisions',
    'project_outcomes',
    'project_plan_steps',
    'project_plans',
    'project_template_clones',
    'project_templates',
    'project_threads',
    'projects',
    'prompt_templates',
    'prompt_versions',
    'research_attempts',
    'research_pricing_snapshots',
    'research_provider_health',
    'research_source_availability_checks',
    'research_source_revisions',
    'research_sources',
    'routines',
    'run_commands',
    'run_descendant_mirrors',
    'run_events',
    'run_plan_approval_bindings',
    'run_plan_revisions',
    'run_policy_snapshots',
    'run_projection_links',
    'run_question_answers',
    'run_question_sets',
    'run_questions',
    'run_research_sources',
    'run_scheduling_permits',
    'run_step_assignments',
    'run_synthesis_manifests',
    'run_tool_invocations',
    'secrets',
    'step_up_sessions',
    'task_checkouts',
    'task_holds',
    'task_thread_items',
    'tasks',
    'team_members',
    'teams',
    'test_users',
    'user_mfa_factors',
    'webhooks',
    'workflows',
    'workspace_lifecycle_events'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC', table_name);
    FOR client_role IN SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated') LOOP
      EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I', table_name, client_role);
    END LOOP;
  END LOOP;
END $$;
